# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          utZhang
paginate:       5
baseurl:        ""
url:            "https://utzhang.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         utZhang
  url:          github.com/utzhang
  email:        utzhang@qq.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/utzhang/utzhang.github.io

# Gems
gems:
  - jekyll-paginate
